[build]
  publish = "out"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://your-backend-on-railway.up.railway.app"

[context.deploy-preview.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://your-backend-on-railway.up.railway.app"
