[phases.setup]
nixPkgs = ['nodejs_18']

[phases.build]
cmds = [
  'rm -rf node_modules',
  'rm -rf package-lock.json',
  'npm cache clean --force',
  'npm install --production --no-optional'
]

[start]
cmd = 'npm start'

[variables]
NODE_ENV = 'production'
NPM_CONFIG_CACHE = '/tmp/.npm'
